import type { Locale } from "../i18n/ui";

export type LocalizedString = Record<Locale, string>;

export interface Tool {
  /** URL slug, e.g. /tools/voice-script-builder */
  slug: string;
  /** Display name per locale */
  name: LocalizedString;
  /** One-line summary shown on cards and as the page subtitle */
  tagline: LocalizedString;
  /** Longer description shown on the detail page */
  description: LocalizedString;
  /** Category label */
  category: LocalizedString;
  /** claude.site embed URL (…/embed) used inside the iframe. Omit for native tools. */
  embedUrl?: string;
  /** Canonical artifact page on claude.ai where a logged-in user can run it.
   * (claude.site only serves the /embed path; its bare URL 404s.) Omit for native tools. */
  artifactUrl?: string;
  /** Native in-browser tool (runs client-side, no iframe). When true, the detail
   * page renders the tool's own component instead of a claude.site embed. */
  native?: boolean;
  /** Whether the tool calls Claude at runtime and therefore needs the viewer to be logged in */
  requiresLogin: boolean;
  /** Date the tool/artifact was last updated (ISO YYYY-MM-DD); bump when republishing */
  updatedAt: string;
}

export const tools: Tool[] = [
  {
    slug: "voice-script-builder",
    name: {
      ko: "한국어 보이스 클로닝 대본 생성기",
      en: "Korean Voice Cloning Script Builder",
      ja: "韓国語ボイスクローニング台本ジェネレーター",
    },
    tagline: {
      ko: "음성 복제 학습용 한국어 녹음 대본을 Claude로 자동 생성합니다.",
      en: "Auto-generates Korean recording scripts for voice-cloning training, powered by Claude.",
      ja: "Claudeで音声クローニング学習用の韓国語録音台本を自動生成します。",
    },
    description: {
      ko: "한글을 초성·중성·종성 단위로 분석해, 모든 발음이 골고루 들어간 자연스러운 A/B 대화 대본을 약 200개 만들어 줍니다. 음성 복제(TTS) 모델 학습을 위한 녹음 대본으로 바로 쓸 수 있고, 생성한 대본은 텍스트로, 전체 데이터는 JSON으로 저장하거나 다시 불러올 수 있습니다.",
      en: "Analyzes Korean Hangul down to its onset/nucleus/coda components and produces around 200 natural A/B dialogue scripts that cover every pronunciation evenly. Use them directly as recording scripts for TTS / voice-cloning model training. Export scripts as plain text and the full dataset as JSON, then re-import any time.",
      ja: "ハングルを初声・中声・終声に分解して分析し、すべての発音が均等に含まれる自然なA/B対話台本を約200本生成します。音声クローニング(TTS)モデル学習用の録音台本としてそのまま使え、生成した台本はテキストで、全データはJSONで保存・読み込みできます。",
    },
    category: {
      ko: "음성 · 오디오",
      en: "Voice · Audio",
      ja: "音声・オーディオ",
    },
    embedUrl:
      "https://claude.site/public/artifacts/a956aeb4-94be-4b24-9706-2948f61c00e1/embed",
    artifactUrl:
      "https://claude.ai/public/artifacts/a956aeb4-94be-4b24-9706-2948f61c00e1",
    requiresLogin: true,
    updatedAt: "2026-05-31",
  },
  {
    slug: "recording-script",
    name: {
      ko: "한국어 녹음 대본 (엄선본)",
      en: "Korean Recording Script (Curated)",
      ja: "韓国語 録音台本(厳選版)",
    },
    tagline: {
      ko: "도구1 대화를 원어민 심사로 엄선한 30분 분량 녹음 대본. 로그인 없이 읽고 내려받으세요.",
      en: "A 30-minute recording script, curated from Tool 1's dialogues by native-speaker review. Read and download, no login.",
      ja: "ツール1の対話をネイティブ審査で厳選した30分分の録音台本。ログイン不要で閲覧・ダウンロード。",
    },
    description: {
      ko: "도구1(Claude 버전)로 생성한 한국어 대화들을, AI로 영어를 비롯한 각국어로 번역했을 때 얼마나 자연스럽고 충실한지(번역 친화성)를 3인이 0.1~5.0점으로 채점해, 상위만 어투(반말·존댓말·평어·격식 등) 균형을 맞춰 약 30분 분량으로 엄선했습니다. 관용구·한국 특유 표현(번역 시 어색)은 낮게, 보편적이고 명료한 대화는 높게 평가됩니다. 로그인·인터넷 없이 보고 복사·다운로드할 수 있으며, 새 대화가 쌓일수록 갱신됩니다.",
      en: "Korean dialogues generated by Tool 1 (the Claude version), scored 0.1–5.0 by three reviewers for how naturally and faithfully each translates into English and other languages via AI. Only the most translation-friendly ones are kept, balanced across speech styles (casual / polite / plain / formal), in a roughly 30-minute set. Idioms and Korean-specific expressions that translate awkwardly are scored low; universal, clearly-structured dialogues score high. View, copy, and download with no login and no internet; refined as more dialogues accumulate.",
      ja: "ツール1(Claude版)で生成した韓国語対話を、AIで英語をはじめ各言語に翻訳したときどれだけ自然で忠実か(翻訳しやすさ)を3人が0.1〜5.0で採点し、上位だけを語調(タメ口・敬語・平叙・フォーマル等)のバランスを取って約30分分に厳選しました。慣用句や韓国特有の表現(翻訳で不自然になるもの)は低く、普遍的で明瞭な対話は高く評価されます。ログイン・インターネット不要で閲覧・コピー・ダウンロードでき、対話が貯まるほど更新されます。",
    },
    category: {
      ko: "음성 · 오디오",
      en: "Voice · Audio",
      ja: "音声・オーディオ",
    },
    native: true,
    requiresLogin: false,
    updatedAt: "2026-06-18",
  },
];

export function getTool(slug: string): Tool | undefined {
  return tools.find((tool) => tool.slug === slug);
}
