import type { Locale } from "../i18n/ui";

export type LocalizedString = Record<Locale, string>;

export interface Tool {
  /** URL slug, e.g. /tools/voice-script-builder */
  slug: string;
  /** Display name per locale */
  name: LocalizedString;
  /** One-line summary shown on cards and as the page subtitle */
  tagline: LocalizedString;
  /** Longer description shown on the detail page */
  description: LocalizedString;
  /** Category label */
  category: LocalizedString;
  /** claude.site embed URL (…/embed) used inside the iframe. Omit for native tools. */
  embedUrl?: string;
  /** Canonical artifact page on claude.ai where a logged-in user can run it.
   * (claude.site only serves the /embed path; its bare URL 404s.) Omit for native tools. */
  artifactUrl?: string;
  /** Native in-browser tool (runs client-side, no iframe). When true, the detail
   * page renders the tool's own component instead of a claude.site embed. */
  native?: boolean;
  /** Whether the tool calls Claude at runtime and therefore needs the viewer to be logged in */
  requiresLogin: boolean;
  /** Date the tool/artifact was last updated (ISO YYYY-MM-DD); bump when republishing */
  updatedAt: string;
}

export const tools: Tool[] = [
  {
    slug: "voice-script-builder",
    name: {
      ko: "한국어 보이스 클로닝 대본 생성기",
      en: "Korean Voice Cloning Script Builder",
      ja: "韓国語ボイスクローニング台本ジェネレーター",
    },
    tagline: {
      ko: "음성 복제 학습용 한국어 녹음 대본을 Claude로 자동 생성합니다.",
      en: "Auto-generates Korean recording scripts for voice-cloning training, powered by Claude.",
      ja: "Claudeで音声クローニング学習用の韓国語録音台本を自動生成します。",
    },
    description: {
      ko: "한글을 초성·중성·종성 단위로 분석해, 모든 발음이 골고루 들어간 자연스러운 A/B 대화 대본을 약 200개 만들어 줍니다. 음성 복제(TTS) 모델 학습을 위한 녹음 대본으로 바로 쓸 수 있고, 생성한 대본은 텍스트로, 전체 데이터는 JSON으로 저장하거나 다시 불러올 수 있습니다.",
      en: "Analyzes Korean Hangul down to its onset/nucleus/coda components and produces around 200 natural A/B dialogue scripts that cover every pronunciation evenly. Use them directly as recording scripts for TTS / voice-cloning model training. Export scripts as plain text and the full dataset as JSON, then re-import any time.",
      ja: "ハングルを初声・中声・終声に分解して分析し、すべての発音が均等に含まれる自然なA/B対話台本を約200本生成します。音声クローニング(TTS)モデル学習用の録音台本としてそのまま使え、生成した台本はテキストで、全データはJSONで保存・読み込みできます。",
    },
    category: {
      ko: "음성 · 오디오",
      en: "Voice · Audio",
      ja: "音声・オーディオ",
    },
    embedUrl:
      "https://claude.site/public/artifacts/a956aeb4-94be-4b24-9706-2948f61c00e1/embed",
    artifactUrl:
      "https://claude.ai/public/artifacts/a956aeb4-94be-4b24-9706-2948f61c00e1",
    requiresLogin: true,
    updatedAt: "2026-05-31",
  },
  {
    slug: "recording-script",
    name: {
      ko: "한국어 녹음 대본 (엄선본)",
      en: "Korean Recording Script (Curated)",
      ja: "韓国語 録音台本(厳選版)",
    },
    tagline: {
      ko: "도구1 대화를 원어민 심사로 엄선한 30분 분량 녹음 대본. 로그인 없이 읽고 내려받으세요.",
      en: "A 30-minute recording script, curated from Tool 1's dialogues by native-speaker review. Read and download, no login.",
      ja: "ツール1の対話をネイティブ審査で厳選した30分分の録音台本。ログイン不要で閲覧・ダウンロード。",
    },
    description: {
      ko: "도구1(Claude 버전)로 생성한 대화들을 모아, 원어민 리뷰어 3인이 0.1~5.0점으로 정밀 채점해 상위만 엄선한 녹음 대본입니다. 모든 발음(초성·중성·종성)이 골고루 들어가도록 음소 균형을 맞춰 약 30분 분량으로 구성했습니다. 소리 내어 읽어 음성 복제(TTS) 모델 학습용 녹음 대본으로 바로 쓸 수 있고, 로그인·인터넷 없이 보고 텍스트로 내려받을 수 있습니다. 새 대화가 쌓일수록 더 엄격하게 갱신됩니다.",
      en: "A recording script assembled from dialogues generated by Tool 1 (the Claude version), where each dialogue is precisely scored 0.1–5.0 by three native-speaker reviewers and only the top ones are kept. It is phoneme-balanced (onset/nucleus/coda) and runs about 30 minutes. Read it aloud as a recording script for TTS / voice-cloning model training; view and download it as plain text with no login and no internet. It is refined further as more dialogues accumulate.",
      ja: "ツール1(Claude版)で生成した対話を集め、ネイティブ3人が0.1〜5.0で精密採点し上位だけを厳選した録音台本です。すべての発音(初声・中声・終声)が均等に入るよう音素バランスを取り、約30分分で構成しています。音読してTTS・音声クローニング学習用の録音台本としてそのまま使え、ログイン・インターネット不要で閲覧・テキストダウンロードできます。対話が貯まるほど厳しく更新されます。",
    },
    category: {
      ko: "음성 · 오디오",
      en: "Voice · Audio",
      ja: "音声・オーディオ",
    },
    native: true,
    requiresLogin: false,
    updatedAt: "2026-06-18",
  },
];

export function getTool(slug: string): Tool | undefined {
  return tools.find((tool) => tool.slug === slug);
}
