import type { Locale } from "../i18n/ui";

export type LocalizedString = Record<Locale, string>;

export interface Tool {
  /** URL slug, e.g. /tools/voice-script-builder */
  slug: string;
  /** Display name per locale */
  name: LocalizedString;
  /** One-line summary shown on cards and as the page subtitle */
  tagline: LocalizedString;
  /** Longer description shown on the detail page */
  description: LocalizedString;
  /** Category label */
  category: LocalizedString;
  /** claude.site embed URL (…/embed) used inside the iframe. Omit for native tools. */
  embedUrl?: string;
  /** Canonical artifact page on claude.ai where a logged-in user can run it.
   * (claude.site only serves the /embed path; its bare URL 404s.) Omit for native tools. */
  artifactUrl?: string;
  /** Native in-browser tool (runs client-side, no iframe). When true, the detail
   * page renders the tool's own component instead of a claude.site embed. */
  native?: boolean;
  /** Whether the tool calls Claude at runtime and therefore needs the viewer to be logged in */
  requiresLogin: boolean;
  /** Date the tool/artifact was last updated (ISO YYYY-MM-DD); bump when republishing */
  updatedAt: string;
}

export const tools: Tool[] = [
  {
    slug: "voice-script-builder",
    name: {
      ko: "한국어 보이스 클로닝 대본 생성기",
      en: "Korean Voice Cloning Script Builder",
    },
    tagline: {
      ko: "음성 복제 학습용 한국어 녹음 대본을 Claude로 자동 생성합니다.",
      en: "Auto-generates Korean recording scripts for voice-cloning training, powered by Claude.",
    },
    description: {
      ko: "한글을 초성·중성·종성 단위로 분석해, 모든 발음이 골고루 들어간 자연스러운 A/B 대화 대본을 약 200개 만들어 줍니다. 음성 복제(TTS) 모델 학습을 위한 녹음 대본으로 바로 쓸 수 있고, 생성한 대본은 텍스트로, 전체 데이터는 JSON으로 저장하거나 다시 불러올 수 있습니다.",
      en: "Analyzes Korean Hangul down to its onset/nucleus/coda components and produces around 200 natural A/B dialogue scripts that cover every pronunciation evenly. Use them directly as recording scripts for TTS / voice-cloning model training. Export scripts as plain text and the full dataset as JSON, then re-import any time.",
    },
    category: {
      ko: "음성 · 오디오",
      en: "Voice · Audio",
    },
    embedUrl:
      "https://claude.site/public/artifacts/a956aeb4-94be-4b24-9706-2948f61c00e1/embed",
    artifactUrl:
      "https://claude.ai/public/artifacts/a956aeb4-94be-4b24-9706-2948f61c00e1",
    requiresLogin: true,
    updatedAt: "2026-05-31",
  },
  {
    slug: "recording-script",
    name: {
      ko: "한국어 녹음 대본 (엄선본)",
      en: "Korean Recording Script (Curated)",
    },
    tagline: {
      ko: "도구1 대화를 원어민 심사로 엄선한 30분 분량 녹음 대본. 로그인 없이 읽고 내려받으세요.",
      en: "A 30-minute recording script, curated from Tool 1's dialogues by native-speaker review. Read and download, no login.",
    },
    description: {
      ko: "도구1(Claude 버전)로 생성한 한국어 대화들을, 소리 내어 읽었을 때 얼마나 자연스러운지(낭독 적합도)를 3인이 0.1~5.0점으로 채점해, 상위만 어투(반말·존댓말·평어·격식 등 8종) 균형과 모든 발음(초성·중성·종성) 커버리지를 맞춰 약 30분 분량으로 엄선한 보이스 클론용 녹음 대본입니다. 한국어로 녹음해 일레븐랩스 같은 곳에서 음성 복제(보이스 클론)에 쓰면, 다양한 억양·감정·발음을 학습한 고급 클론을 만들 수 있습니다. 로그인·인터넷 없이 보고 복사·다운로드할 수 있으며, 새 대화가 쌓일수록 더 좋은 것으로 갱신됩니다.",
      en: "Korean dialogues generated by Tool 1 (the Claude version), scored 0.1–5.0 by three reviewers for how natural each sounds read aloud. Only the top ones are kept — balanced across 8 speech styles (casual / polite / plain / formal …) and across every phoneme (onset / nucleus / coda) — in a roughly 30-minute set. Record it in Korean and use it to build a high-quality voice clone (e.g. on ElevenLabs) that has learned varied intonation, emotion, and pronunciation. View, copy, and download with no login and no internet; it upgrades as more dialogues accumulate.",
    },
    category: {
      ko: "음성 · 오디오",
      en: "Voice · Audio",
    },
    native: true,
    requiresLogin: false,
    updatedAt: "2026-06-18",
  },
];

export function getTool(slug: string): Tool | undefined {
  return tools.find((tool) => tool.slug === slug);
}
